/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penilaianmahasiswa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author sad
 */
public class FormNilai extends javax.swing.JFrame {

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        disableInput();
        
        btnBatal.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        
        checkData();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCariNIM = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnTampilSeluruhData = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        txtNilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNilai = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        cbKodeMK = new javax.swing.JComboBox<>();
        cbIndeks = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(728, 435));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Nilai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pencarian Nilai Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Masukkan NIM");

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTampilSeluruhData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTampilSeluruhData.setText("Tampilkan Seluruh Data");
        btnTampilSeluruhData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilSeluruhDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtCariNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(btnTampilSeluruhData)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnTampilSeluruhData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kode Mata Kuliah");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nilai");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Indeks");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Keterangan");

        tableNilai.setModel(newTableModel);
        tableNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNilai);

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        cbKodeMK.setModel(newCbModel());

        cbIndeks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNilai)
                            .addComponent(cbKodeMK, 0, 101, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(cbKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah)
                    .addComponent(btnBatal)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final KonfigurasiDB conf = new KonfigurasiDB();
    private final String DATABASE = conf.getDBName();
    private final String USER = conf.getDBUser();
    private final String PASSWORD = conf.getDBPassword();
    
    private final javax.swing.table.DefaultTableModel newTableModel = createNewTableModel();
    private int selectedRow = 0;
    
    private javax.swing.table.DefaultTableModel createNewTableModel(){
        return new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"No", "NIM", "Kode Mata Kuliah", "Nilai", "Indeks", "Keterangan"}
        ){
            boolean[] canEdit = new boolean[] {false, false, false, false, false, false};
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }

    private javax.swing.ComboBoxModel newCbModel(){
        String[] cbItems = {};
        ArrayList<String> cbElement = new ArrayList<>();
        try (
            Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery("SELECT kd_mk FROM t_mata_kuliah");
        ){  
            while(res.next()){
                cbElement.add(res.getString(1));
            }
            cbItems = cbElement.toArray(new String[0]);
            res.close();
            st.close();
            con.close();
        } catch(SQLException e) {
            javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
        }
        return new javax.swing.DefaultComboBoxModel(cbItems);
    }
    
    private void checkData(){
        try (
            Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery("SELECT * FROM t_nilai");
        ){  
            if(!res.next()){
                st.executeUpdate("INSERT INTO t_nilai (nim) SELECT nim FROM t_mahasiswa");
            }
            res.close();
            st.close();
            con.close();
        } catch(SQLException e) {
            javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
        }
    }
    
    private void loadTableData(){
        try (
            Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery("SELECT * FROM t_nilai");        
        ){  
            String data[] = new String[6];
            while(res.next()){
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                data[5] = res.getString(6);
                newTableModel.addRow(data);
            }
            res.close();
            st.close();
            con.close();
        } catch(SQLException e) {
            javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
        }
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try (
            Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
            Statement st = con.createStatement();
        ){
            final String QUERY = "UPDATE t_nilai SET kd_mk = NULL, nilai = NULL, indeks = NULL, ket = NULL WHERE nim = '"+newTableModel.getValueAt(selectedRow, 1).toString()+"'";
            st.executeUpdate(QUERY);
            st.close();
            con.close();
            
            newTableModel.setValueAt(null, selectedRow, 2);
            newTableModel.setValueAt(null, selectedRow, 3);
            newTableModel.setValueAt(null, selectedRow, 4);
            newTableModel.setValueAt(null, selectedRow, 5);
            
            textCleanup();
            disableInput();
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            btnBatal.setEnabled(false);
            btnKeluar.setEnabled(true);
        } catch(SQLException e) {
            javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if(txtNilai.getText().isEmpty() || txtKeterangan.getText().isEmpty()){
            javax.swing.JOptionPane.showConfirmDialog(this, "Data tidak boleh ada yang kosong, silakan dilengkapi!");
        } else {
            try (
                Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
                Statement st = con.createStatement();
            ){
                final String QUERY = "UPDATE t_nilai SET kd_mk = '"+cbKodeMK.getSelectedItem()
                        + "', nilai = '"+txtNilai.getText()
                        + "', indeks = '"+cbIndeks.getSelectedItem()
                        + "', ket = '"+txtKeterangan.getText()
                        + "' WHERE nim = '"+newTableModel.getValueAt(selectedRow, 1).toString()+"'";
                st.executeUpdate(QUERY);
                
                newTableModel.setValueAt(cbKodeMK.getSelectedItem(), selectedRow, 2);
                newTableModel.setValueAt(txtNilai.getText(), selectedRow, 3);
                newTableModel.setValueAt(cbIndeks.getSelectedItem(), selectedRow, 4);
                newTableModel.setValueAt(txtKeterangan.getText(), selectedRow, 5);
                
		textCleanup();
                disableInput();
		btnHapus.setEnabled(false);
                btnUbah.setEnabled(false);
                btnBatal.setEnabled(false);
                btnKeluar.setEnabled(true);
            } catch(SQLException e) {
		javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        textCleanup();
        disableInput();
        btnHapus.setEnabled(false);
        btnUbah.setEnabled(false);
        btnBatal.setEnabled(false);
        btnKeluar.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        FormUtama formUtama= new FormUtama();
        formUtama.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        newTableModel.setRowCount(0);
        try (
            Connection con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery("SELECT * FROM t_nilai WHERE nim = '"+txtCariNIM.getText()+"'");
        ){  
            String data[] = new String[6];
            while(res.next()){
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                data[5] = res.getString(6);
                newTableModel.addRow(data);
            }
            res.close();
            st.close();
            con.close();
        } catch(SQLException e) {
            javax.swing.JOptionPane.showConfirmDialog(this, e.toString());
        }
        txtCariNIM.setText("");
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTampilSeluruhDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilSeluruhDataActionPerformed
        newTableModel.setRowCount(0);
        loadTableData();
    }//GEN-LAST:event_btnTampilSeluruhDataActionPerformed

    private void tableNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNilaiMouseClicked
        if(evt.getClickCount() == 1){
            selectedRow = tableNilai.getSelectedRow();
            txtNilai.requestFocus();
            btnHapus.setEnabled(true);
            btnUbah.setEnabled(true);
            btnBatal.setEnabled(true);
            btnKeluar.setEnabled(false);
            enableInput();
            showSelected();
        }
    }//GEN-LAST:event_tableNilaiMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        FormUtama formUtama = new FormUtama();
        formUtama.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void showSelected(){
        String kodeMKVal = "";
        String nilaiVal = "";
        String indeksVal = "";
        String ketVal = "";
        try {
            kodeMKVal = newTableModel.getValueAt(selectedRow, 2).toString();
            nilaiVal = newTableModel.getValueAt(selectedRow, 3).toString();
            indeksVal = newTableModel.getValueAt(selectedRow, 4).toString();
            ketVal = newTableModel.getValueAt(selectedRow, 5).toString();
        } catch (NullPointerException e){
            
        }
        cbKodeMK.setSelectedItem(kodeMKVal);
        txtNilai.setText(nilaiVal);
        cbIndeks.setSelectedItem(indeksVal);
        txtKeterangan.setText(ketVal);
    }
    
    private void textCleanup(){
        txtNilai.setText("");
        txtKeterangan.setText("");
    }
    
    private void disableInput(){
        cbKodeMK.setEnabled(false);
        txtNilai.setEnabled(false);
        cbIndeks.setEnabled(false);
        txtKeterangan.setEnabled(false);
    }
    
    private void enableInput(){
        cbKodeMK.setEnabled(true);
        txtNilai.setEnabled(true);
        cbIndeks.setEnabled(true);
        txtKeterangan.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTampilSeluruhData;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbIndeks;
    private javax.swing.JComboBox<String> cbKodeMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNilai;
    private javax.swing.JTextField txtCariNIM;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNilai;
    // End of variables declaration//GEN-END:variables
}
